server.port=8080

roboflow.api.key=M30Rc5mxODzOvU7DheKu


redmine.url=https://maravicognjen.redminecloud.net
redmine.api.key=oOhaoqYcVrmBGRPyVzbR


spring.datasource.url=jdbc:h2:file:./data/mappingdb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true


spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB