server.port=8080

roboflow.api.key=soYpmL6L7ceC0YgGvX8L
roboflow.workspace=ognjens-workspace-rujhp

redmine.url=https://maravicognjen.redminecloud.net
redmine.api.key=71335c919504ed1f8e04f6acefa4f4ef4aa170d0

spring.datasource.url=jdbc:h2:file:./data/mappingdb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB


